[project]
name = "publication-tracker"
version = "1.9.8"
requires-python = ">= 3.12"
dependencies = [
    "bibtexparser",
    "cryptography",
    "Django~=6.0",
    "django-bootstrap5",
    "django-cors-headers",
    "django-filter",
    "djangorestframework",
    "drf-spectacular",
    "fontawesomefree",
    "markdown",
    "psycopg2-binary",
    "pyjwt",
    "python-dateutil",
    "requests",
    "uwsgi",
]
