# Generated by Django 6.0.2 on 2026-03-01 19:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_expires', models.DateTimeField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('cookie', 'Cookie'), ('token', 'Token')], default='cookie', max_length=24)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('cilogon_id', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('fabric_roles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255))),
                ('name', models.CharField(blank=True, max_length=255)),
                ('projects', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255))),
                ('uuid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskTimeoutTracker',
            fields=[
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField()),
                ('name', models.CharField(max_length=255)),
                ('timeout_in_seconds', models.IntegerField(default=0)),
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_timeout_tracker',
                'ordering': ('name',),
            },
        ),
    ]
