# Generated by Django 6.0.8 on 2026-08-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tasktimeouttracker',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_task_timeout_tracker_name'),
        ),
    ]
