# Generated by Django 6.0.2 on 2026-03-01 19:37

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubSimple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_name', models.TextField(blank=True, default=None, max_length=5000, null=True)),
                ('project_uuid', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title', models.TextField(max_length=5000)),
                ('uuid', models.CharField(max_length=255)),
                ('venue', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('year', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_created_by', to='apiuser.apiuser')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact_modified_by', to='apiuser.apiuser')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('link__isnull', True)), fields=('title',), name='unique_publication_link_is_null'), models.UniqueConstraint(fields=('title', 'link'), name='unique_publication')],
            },
        ),
    ]
