"""
Django settings for publicationtrkr project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from django.core.exceptions import ImproperlyConfigured
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fails closed. This used to fall back to a hardcoded 'django-insecure-...' literal,
# which is committed here and mirrored to the public repository -- so a deployment that
# forgot DJANGO_SECRET_KEY ran production on a publicly known key, signing sessions and
# password-reset tokens with it, and said nothing. Every other required variable in this
# file already raises at import when unset; this one now matches.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is not set (see env.template)')

# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('DJANGO_DEBUG').casefold() == 'true':
    DEBUG = True
else:
    DEBUG = False

# SECURITY WARNING: don't run with API debug turned on in production!
if os.getenv('API_DEBUG').casefold() == 'true':
    API_DEBUG = True
else:
    API_DEBUG = False

# Hosts and CORS origins are environment-driven so that no deployment has to
# edit this file. Both variables are comma-separated. ALLOWED_HOSTS is always
# added to the loopback defaults; CORS_ALLOWED_ORIGINS only outside DEBUG -- see
# below.


def _csv_env(name: str) -> list[str]:
    return [v.strip() for v in os.getenv(name, '').split(',') if v.strip()]


ALLOWED_HOSTS = list(dict.fromkeys(
    ["localhost", "127.0.0.1"] + _csv_env('DJANGO_ALLOWED_HOSTS')
))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',
    'rest_framework',
    'corsheaders',  # django cors headers
    'drf_spectacular',
    'django_bootstrap5',  # django bootstrap
    'fontawesomefree',  # fontawesome free version
    'publicationtrkr.apps.apiuser',  # app: apiuser
    'publicationtrkr.apps.pubsimple',  # app: pubsimple
    'publicationtrkr.apps.publications',  # app: publications
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    # DRF wraps every view in csrf_exempt, so CsrfViewMiddleware above never protects
    # /api/. This restores the part of that protection a cookie-authenticated API needs.
    'publicationtrkr.server.middleware.ApiSimpleRequestGuardMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# Loopback origins are a development convenience and were permanently in the production
# allowlist. Combined with the Access-Control-Allow-Credentials header nginx used to set
# for every origin it answered, that let anything the victim was running locally over
# https make credentialed cross-origin reads against production. Both halves are fixed:
# nginx no longer asserts that header, and these entries are conditional on DEBUG.
#
# This narrows CSRF_TRUSTED_ORIGINS below by the same two entries. Nothing is lost:
# Django always trusts a request's own origin, so same-origin form posts -- every POST
# this application serves -- do not consult that list at all.
_LOOPBACK_ORIGINS = ['https://127.0.0.1', 'https://localhost'] if DEBUG else []

CORS_ALLOWED_ORIGINS = list(dict.fromkeys(
    _LOOPBACK_ORIGINS + _csv_env('DJANGO_CORS_ALLOWED_ORIGINS')
))

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = (
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "DNT",
    "User-Agent",
    "X-Requested-With",
    "If-Modified-Since",
    "Cache-Control",
    "Range",
)

# Was CORS_AlLOW_CREDENTIALS (lowercase l) and therefore inert -- Django never read it,
# so credentialed cross-origin requests have in practice been disallowed at this layer.
# Keeping that behaviour rather than silently switching it on by fixing the spelling:
# nginx sets Access-Control-Allow-Credentials itself, and which layer owns that header
# is a deployment decision, not a typo fix.
CORS_ALLOW_CREDENTIALS = False

# Transport and cookie hardening. None of this was set: no SECURE_*, no CSRF_COOKIE_*,
# no SESSION_COOKIE_*, no X_FRAME_OPTIONS.
#
# TLS terminates at nginx, which forwards X-Forwarded-Proto: https. Without
# SECURE_PROXY_SSL_HEADER Django believes every request is plain http, so it would
# refuse to set Secure cookies and request.is_secure() would be wrong.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Secure cookies off in DEBUG so local http development still works.
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

# Django 4+ requires the scheme here for cross-origin POSTs. Derived from the same
# env var as CORS so a deployment configures one list, not two.
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'same-origin'

# HSTS defaults to OFF. Enabling it is effectively irreversible for anyone who has
# visited -- browsers honour max-age regardless of what the site serves later -- so it
# is opt-in per deployment rather than a default that ships and surprises someone.
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_HSTS_SECONDS > 0
SECURE_HSTS_PRELOAD = False

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': int(os.getenv('REST_FRAMEWORK_PAGE_SIZE')),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # There was no throttling of any kind. Identity here comes from get_api_user(),
    # not request.user, so DRF sees every caller as anonymous -- AnonRateThrottle
    # therefore buckets by IP, which is the right granularity for an API that is
    # anonymously readable.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': os.getenv('THROTTLE_ANON', '120/min'),
        'bulk': os.getenv('THROTTLE_BULK', '6/hour'),
    },
}

SPECTACULAR_SETTINGS = {
    # 'PREPROCESSING_HOOKS': ['artifactmgr.server.api_filters.preprocessing_filter_spec'],
    'TITLE': 'FABRIC Publication Tracker',
    'DESCRIPTION': 'A platform for sharing FABRIC related publications.',
    'VERSION': '1.12.1',
    'SERVE_INCLUDE_SCHEMA': False,
    # OTHER SETTINGS
    'COMPONENT_SPLIT_REQUEST': True,
}

ROOT_URLCONF = 'publicationtrkr.server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'publicationtrkr/templates'),
            os.path.join(BASE_DIR, 'publicationtrkr/templates/publicationtrkr'),
            os.path.join(BASE_DIR, 'publicationtrkr/templates/publications'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'publicationtrkr.server.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('POSTGRES_HOST'),
        'PORT': os.getenv('POSTGRES_PORT')
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Login / Logout settings
LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

LOGOUT_URL = '/logout'
LOGOUT_REDIRECT_URL = '/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'publicationtrkr/server/static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
